(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const body=document.body, editor=$('#editor'), toast=$('#toast');let toastTimer;
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2000)}
function openPortfolio(id='hero'){body.classList.add('portfolio-open');setTimeout(()=>go(id,false),20)}
function showDesktop(){body.classList.remove('portfolio-open');closePopups();closeModal('#trashWindow');closeModal('#txtWindow')}
$$('[data-action=desktop]').forEach(b=>b.onclick=showDesktop);$('#desktopBtn').onclick=showDesktop;$('#taskPortfolio').onclick=()=>openPortfolio();$$('[data-action=portfolio]').forEach(b=>b.onclick=()=>openPortfolio());
$('#fullscreenBtn').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{notify('Tam ekran tarayıcı tarafından engellendi.')}};
function updateClock(){const n=new Date(),time=n.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}),secs=n.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),date=n.toLocaleDateString('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'});$('#deskTime').textContent=time;$('#deskDate').textContent=date;$('#clockBig').textContent=secs;$('#clockDate').textContent=n.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#mobileTime').textContent=time}updateClock();setInterval(updateClock,1000);
const popups=$$('.popup');function closePopups(){popups.forEach(p=>p.classList.remove('open'))}function togglePopup(el){const was=el.classList.contains('open');closePopups();if(!was)el.classList.add('open')}
$('#startBtn').onclick=e=>{e.stopPropagation();togglePopup($('#startMenu'))};$('#searchBtn').onclick=e=>{e.stopPropagation();togglePopup($('#searchPanel'));setTimeout(()=>$('#desktopSearch').focus(),0)};$('#clockBtn').onclick=e=>{e.stopPropagation();updateClock();togglePopup($('#clockPanel'))};$('#desktop').onclick=e=>{if(!e.target.closest('.popup')&&!e.target.closest('.taskbar')&&!e.target.closest('.window-modal'))closePopups()};$('#restartBtn').onclick=()=>location.reload();
function openModal(sel){$(sel).classList.add('open')}function closeModal(sel){$(sel).classList.remove('open')}$('#trashIcon').onclick=()=>openModal('#trashWindow');$('#txtFile').onclick=()=>openModal('#txtWindow');$$('[data-close]').forEach(b=>b.onclick=()=>closeModal('#'+b.dataset.close));
$$('[data-folder]').forEach(b=>b.onclick=()=>notify(`'${b.dataset.folder}' klasörünü daha sonra doldurabiliriz.`));
$$('[data-start]').forEach(b=>b.onclick=()=>{closePopups();const a=b.dataset.start;if(a==='portfolio')openPortfolio();else if(a==='projects')notify("'Yapılan Projeler' klasörünü daha sonra doldurabiliriz.");else if(a==='backups')notify("'Yedeklerim' klasörünü daha sonra doldurabiliriz.");else if(a==='trash')openModal('#trashWindow');else if(a==='settings'){openPortfolio();setPanel('settings')}else if(a==='terminal'){openPortfolio();toggleTerminal(true)}});
const desktopItems=[['Portfolio','Uygulama',()=>openPortfolio()],['Yapılan Projeler','Klasör',()=>notify("'Yapılan Projeler' klasörünü daha sonra doldurabiliriz.")],['Yedeklerim','Klasör',()=>notify("'Yedeklerim' klasörünü daha sonra doldurabiliriz.")],['Araçlar','Klasör',()=>notify("'Araçlar' klasörünü daha sonra doldurabiliriz.")],['Tasarım Arşivi','Klasör',()=>notify("'Tasarım Arşivi' klasörünü daha sonra doldurabiliriz.")],['Odium Assets','Klasör',()=>notify("'Odium Assets' klasörünü daha sonra doldurabiliriz.")],['Çöp Kutusu','Sistem',()=>openModal('#trashWindow')],['nowiland.txt','Metin',()=>{openModal('#trashWindow');openModal('#txtWindow')}],['Terminal','Uygulama',()=>{openPortfolio();toggleTerminal(true)}]];
function desktopSearch(){const q=$('#desktopSearch').value.toLocaleLowerCase('tr'),box=$('#desktopResults');box.innerHTML='';desktopItems.filter(x=>!q||x[0].toLocaleLowerCase('tr').includes(q)||x[1].toLocaleLowerCase('tr').includes(q)).forEach(x=>{const b=document.createElement('button');b.className='search-result';b.innerHTML=`<span>${x[0]}</span><small>${x[1]}</small>`;b.onclick=()=>{closePopups();x[2]()};box.appendChild(b)})}$('#desktopSearch').oninput=desktopSearch;desktopSearch();
const sections=$$('.ide-section'),files=$$('.file[href^="#"]'),tabs=$('#tabs'),crumb=$('#crumb');let current='hero',openTabs=['hero'];
function fileFor(id){return $('#'+id)?.dataset.file||id}function renderTabs(){tabs.innerHTML='';openTabs.forEach(id=>{const b=document.createElement('button');b.className='tab'+(id===current?' active':'');b.innerHTML=`<span>${fileFor(id)}</span><b>×</b>`;b.onclick=e=>{if(e.target.tagName==='B'){if(openTabs.length===1)return;const was=id===current;openTabs=openTabs.filter(x=>x!==id);if(was)go(openTabs.at(-1),false);else renderTabs()}else go(id)};tabs.appendChild(b)})}
function go(id,smooth=true){const s=$('#'+id);if(!s)return;current=id;if(!openTabs.includes(id))openTabs.push(id);crumb.textContent=fileFor(id);files.forEach(f=>f.classList.toggle('active',f.getAttribute('href')==='#'+id));renderTabs();s.scrollIntoView({behavior:smooth?'smooth':'auto',block:'start'})}renderTabs();
files.forEach(f=>f.onclick=e=>{e.preventDefault();go(f.getAttribute('href').slice(1))});$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const obs=new IntersectionObserver(es=>{const hit=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;current=hit.target.id;crumb.textContent=fileFor(current);files.forEach(f=>f.classList.toggle('active',f.getAttribute('href')==='#'+current));if(openTabs.includes(current))renderTabs()},{root:editor,threshold:[.2,.5],rootMargin:'-5% 0px -60%'});sections.forEach(s=>obs.observe(s));
function setPanel(name){$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));$$('[data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===name))}$$('[data-side]').forEach(b=>b.onclick=()=>setPanel(b.dataset.side));
$('#ideSearch').oninput=()=>{const q=$('#ideSearch').value.toLocaleLowerCase('tr'),box=$('#ideSearchResults');box.innerHTML='';if(!q)return;sections.filter(s=>s.innerText.toLocaleLowerCase('tr').includes(q)).forEach(s=>{const b=document.createElement('button');b.className='ide-hit';b.textContent=fileFor(s.id);b.onclick=()=>go(s.id);box.appendChild(b)})};
$$('[data-theme]').forEach(b=>b.onclick=()=>{document.documentElement.dataset.theme=b.dataset.theme;localStorage.setItem('theme',b.dataset.theme)});document.documentElement.dataset.theme=localStorage.getItem('theme')||'dark';
const terminal=$('#terminal'),termOut=$('#termOut'),termIn=$('#termInput');function toggleTerminal(force){terminal.classList.toggle('open',force??!terminal.classList.contains('open'));if(terminal.classList.contains('open'))setTimeout(()=>termIn.focus(),150)}$('#terminalBtn').onclick=()=>toggleTerminal(true);$('#statusTerminal').onclick=()=>toggleTerminal();$('#terminalClose').onclick=()=>toggleTerminal(false);function print(t){termOut.textContent+='\n'+t;termOut.scrollTop=termOut.scrollHeight}function command(raw){const [cmd,...rest]=raw.trim().split(/\s+/),arg=rest.join(' ');if(!cmd)return;print(`➜ ~ ${raw}`);if(cmd==='help')print('help, whoami, projects, skills, about, open <file>, desktop, theme <dark|light|hc>, clear, date');else if(cmd==='whoami')print('hasan — full stack developer @ Odium Stüdyo | web designer + reverse engineer | C++');else if(['projects','skills','about'].includes(cmd)){go(cmd==='skills'?'skills':cmd);print(fileFor(cmd==='skills'?'skills':cmd)+' açıldı.')}else if(cmd==='desktop')showDesktop();else if(cmd==='date')print(new Date().toLocaleString('tr-TR'));else if(cmd==='clear')termOut.textContent='';else if(cmd==='theme'&&['dark','light','hc'].includes(arg)){document.documentElement.dataset.theme=arg;print('Tema: '+arg)}else if(cmd==='open'){const s=sections.find(s=>fileFor(s.id).toLowerCase()===arg.toLowerCase());s?(go(s.id),print(fileFor(s.id)+' açıldı.')):print('Dosya bulunamadı: '+arg)}else print("command not found: "+cmd)}termIn.onkeydown=e=>{if(e.key==='Enter'){const v=termIn.value;termIn.value='';command(v)}};
$('#tourBtn').onclick=()=>{toggleTerminal(true);print('> portfolio-tour başlatıldı');['hero','about','skills','projects','experience'].forEach((id,i)=>setTimeout(()=>print('✓ '+fileFor(id)+' ready'),i*180));setTimeout(()=>go('projects'),850)};
const palette=$('#palette'),palIn=$('#paletteInput'),palList=$('#paletteList');const cmds=sections.map(s=>[`Dosya Aç: ${fileFor(s.id)}`,()=>go(s.id)]).concat([['Masaüstünü Göster',showDesktop],['Terminali Aç/Kapat',()=>toggleTerminal()],['Tema: Dark',()=>document.documentElement.dataset.theme='dark'],['Tema: Light',()=>document.documentElement.dataset.theme='light'],['Tema: High Contrast',()=>document.documentElement.dataset.theme='hc']]);function renderPal(){const q=palIn.value.replace(/^>/,'').toLocaleLowerCase('tr');palList.innerHTML='';cmds.filter(c=>c[0].toLocaleLowerCase('tr').includes(q)).forEach(c=>{const d=document.createElement('div');d.className='palette-item';d.textContent=c[0];d.onclick=()=>{palette.classList.remove('open');c[1]()};palList.appendChild(d)})}function openPal(){palette.classList.add('open');palIn.value='';renderPal();setTimeout(()=>palIn.focus(),0)}$('#commandBtn').onclick=openPal;$('#heroCommand').onclick=openPal;palIn.oninput=renderPal;palIn.onkeydown=e=>{if(e.key==='Enter')palList.firstElementChild?.click();if(e.key==='Escape')palette.classList.remove('open')};palette.onclick=e=>{if(e.target===palette)palette.classList.remove('open')};
function typewriter(el){if(!el)return;const names=['Hasan','thedrowned','apexlions16'],near={a:'sqwz',b:'vghn',c:'xdfv',d:'serfcx',e:'wsdr',f:'drtgvc',g:'ftyhbv',h:'gyujnb',i:'ujko',j:'huikmn',k:'jiolm',l:'kop',m:'njk',n:'bhjm',o:'iklp',p:'ol',q:'wa',r:'edft',s:'awedxz',t:'rfgy',u:'yhji',v:'cfgb',w:'qase',x:'zsdc',y:'tghu',z:'asx','1':'2q','2':'13w','6':'57y'};let wi=0;el.textContent=names[0];const sleep=m=>new Promise(r=>setTimeout(r,m));(async()=>{await sleep(1400);for(;;){while(el.textContent.length){el.textContent=el.textContent.slice(0,-1);await sleep(55+Math.random()*25)}await sleep(250);wi=(wi+1)%names.length;const w=names[wi],typo=Math.random()<.5?1+Math.floor(Math.random()*Math.max(1,w.length-2)):-1;for(let i=0;i<w.length;i++){if(i===typo){const opts=near[w[i].toLowerCase()]||'qwerty';el.textContent+=opts[Math.floor(Math.random()*opts.length)];await sleep(220);el.textContent=el.textContent.slice(0,-1);await sleep(70)}el.textContent+=w[i];await sleep(80+Math.random()*55)}await sleep(1450)}})()}typewriter($('#typeName'));typewriter($('#mobileName'));
const mScroll=$('#mobileScroll');$$('[data-mgo]').forEach(b=>b.onclick=()=>{const t=$('#'+b.dataset.mgo);t?.scrollIntoView({behavior:'smooth'});$$('[data-mgo]').forEach(x=>x.classList.toggle('active',x===b))});if(mScroll){const mo=new IntersectionObserver(es=>{const hit=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(hit)$$('[data-mgo]').forEach(b=>b.classList.toggle('active',b.dataset.mgo===hit.target.id))},{root:mScroll,threshold:[.3,.55],rootMargin:'-12% 0px -55%'});['m-home','m-skills','m-projects','m-work'].forEach(id=>mo.observe($('#'+id)))}
document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&(e.key.toLowerCase()==='p'||e.key.toLowerCase()==='k')){e.preventDefault();openPal()}if(mod&&e.key==='`'){e.preventDefault();toggleTerminal()}if(e.key==='Escape'){closePopups();$$('.window-modal.open').forEach(x=>x.classList.remove('open'));palette.classList.remove('open')}});
})();